---
booktitle: Proceedings of the 32nd International Conference on Algorithmic Learning
  Theory
shortname: ALT
year: '2021'
volume: 132
start: 2021-03-16
end: 2021-03-19
published: 2021-03-01
url: http://proceedings.mlr.press
conference_number: '32'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: ALT2021
month: 0
cycles: false
bibtex_editor: Feldman, Vitaly and Ligett, Katrina and Sabato, Sivan
editor:
- given: Vitaly
  family: Feldman
- given: Katrina
  family: Ligett
- given: Sivan
  family: Sabato
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 32nd International Conference on Algorithmic Learning Theory
    Held in Virtual Conference, Worldwide on 16-19 March 2021

  Published as Volume 132 by the Proceedings of Machine Learning Research on 01 March 2021.

  Volume Edited by:
    Vitaly Feldman
    Katrina Ligett
    Sivan Sabato

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 16--19 Mar
author:
  name: PMLR
baseurl: "/v132"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v132
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: Algorithmic Learning Theory
  url: 
  location: Virtual Conference, Worldwide
  dates:
  - 2021-03-16
  - 2021-03-17
  - 2021-03-18
  - 2021-03-19
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v132/alt21.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v132/alt21.bib
